apiVersion: apps/v1
kind: Deployment
metadata:
  name: proveedor-deployment
  labels:
    app: proveedor-deployment
spec:
  selector:
    matchLabels:
      app: proveedor-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: proveedor-deployment
    spec:
      containers:
        - name: proveedor
          image: agustinharistoy/proveedor_docker
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:8081
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://proveedor-db-service:5432/proveedor_db
            - name: SPRING_DATASOURCE_USERNAME
              value: username
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.prefer-ip-address
              value: "true"

